# architecture
arch: vit_base
enc_arch: MAEViTEncoder
dec_arch: MAEViTDecoder

# wandb
proj_name: mae3d
run_name: ${proj_name}_${arch}_${dataset}
disable_wandb: 0
wandb_id:

# dataset
dataset: acdc
pkl_list: "dataset3d.pkl"
data_path: "/home/shqin/acdcSSL/dataset/mae3d"

# output
output_dir: outputs/${run_name}
ckpt_dir: ${output_dir}/ckpts

# data preprocessing
resize_x: 200
resize_y: 256
resize_z: 12
patch_x: 16
patch_y: 16
patch_z: 3
roi_x: 160
roi_y: 160
roi_z: 9
RandFlipd_prob: 0.2
# RandRotate90d_prob: 0.2
num_samples: 4

# trainer
trainer_name: MAE3DTrainer
batch_size: 16
epochs: 5000
start_epoch: 0
warmup_epochs: 100
val_batch_size: 1
workers: 8
resume:

# model
patchembed: 'PatchEmbed3D'
pos_embed_type: 'sincos'
mask_ratio: 0.50
input_size: ${roi_x}
patch_size: 16
in_chans: 1
encoder_embed_dim: 768
encoder_depth: 12
encoder_num_heads: 12
decoder_embed_dim: 384
decoder_depth: 8
decoder_num_heads: 12

# optimizer
type: adamw
lr: 6.4e-3
beta1: 0.9
beta2: 0.95
weight_decay: 0.05

# logging
vis_freq: 100
save_freq: 500
print_freq: 1


multiprocessing_distributed: false
distributed:
gpu: 0
rank: 0
seed: 
test: false